### ISSUE TITLE
Writing mistakes in the text of the project description!

### ISSUE THREAD

**Issue by QuestionPython** [yoosofan/REXX#1]
Hello, Mr Ahmad Yoosofan.

Description Text of this Project : 
```
This is my BS project on writing aد interpreter for REXX programming language on DOS operating system under the supervision of Dr. Ahmad Towhidi
```

There is a persian letter(`د`) after `on writing a` .

Thanks so much.

**Comment by yoosofan** [comment]
Hello,
Thank you.
I changed the topic of my Rexx project.
Kind Regards,

--
  ahmad yoosofan
  yoosofan@myfastmail.com



On Tue, Dec 19, 2017, at 4:01 AM, questionpython wrote:
> Hello, Mr Ahmad Yoosofan.


> Description Text of this Project :


> This is my BS project on writing aد interpreter for REXX
> programming language on DOS operating system under the supervision
> of Dr. Ahmad Towhidi
>> There is a persian letter(د) after on writing a .


> Thanks so much.


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/yoosofan/REXX/issues/1
